"""Loader — reads graph.md files and builds a session prompt for AI agents."""

import sys
from pathlib import Path

import pyperclip
from rich.console import Console
from rich.panel import Panel
from rich.text import Text

console = Console(stderr=True)  # status output to stderr; prompt goes to stdout

SESSION_OPENER = """\
# Relic Knowledge Graph — Session Context

You are working on this codebase. The knowledge graph(s) below were generated by
analysing the source code. Read them carefully before responding.

After reading, state:
1. Confidence score (1-10) for each subproject
2. What you understand well
3. Any gaps or uncertainties
4. Confirm you are ready to work

---

{graphs}

---

You have read the knowledge graph(s) above. You are now ready to assist with this codebase.
"""


def read_graph(subproject_name: str, knowledge_dir: Path) -> str:
    """Read the graph.md for a subproject and return its content.

    Raises FileNotFoundError if the graph does not exist.
    """
    graph_path = knowledge_dir / subproject_name / "graph.md"
    if not graph_path.exists():
        raise FileNotFoundError(
            f"No graph found for '{subproject_name}' at {graph_path}. "
            f"Run `relic --refresh {subproject_name}` to generate it."
        )
    return graph_path.read_text(encoding="utf-8")


def build_prompt(subproject_names: list[str], knowledge_dir: Path) -> str:
    """Build the full session prompt by loading all requested subproject graphs.

    Returns the assembled prompt string.
    Raises FileNotFoundError if any graph is missing.
    """
    sections = []
    for name in subproject_names:
        content = read_graph(name, knowledge_dir)
        sections.append(f"<!-- SUBPROJECT: {name} -->\n\n{content}")

    combined = "\n\n---\n\n".join(sections)
    return SESSION_OPENER.format(graphs=combined)


def load_and_copy(subproject_names: list[str], knowledge_dir: Path) -> None:
    """Load graphs, print prompt to stdout, and copy to clipboard.

    Stdout: the full session prompt — coding agents (Claude Code, Copilot, etc.)
            read this directly from the tool output.
    Clipboard: same content — for web-based AI sessions where you paste manually.
    Stderr: status panel shown to the user.
    """
    try:
        prompt = build_prompt(subproject_names, knowledge_dir)
    except FileNotFoundError as exc:
        console.print(f"[bold red]Error:[/bold red] {exc}")
        raise SystemExit(1)

    # Print to stdout — agents read this from the bash tool result.
    print(prompt)

    # Also copy to clipboard for web-based AI sessions.
    try:
        pyperclip.copy(prompt)
        clipboard_status = "copied to clipboard"
    except Exception:
        clipboard_status = "clipboard unavailable"

    names_str = ", ".join(subproject_names)
    char_count = len(prompt)

    console.print(
        Panel(
            Text.assemble(
                ("Knowledge graph loaded\n\n", "bold green"),
                ("Subprojects: ", "bold"),
                (names_str + "\n", "cyan"),
                ("Characters:  ", "bold"),
                (f"{char_count:,}\n", "cyan"),
                ("Clipboard:   ", "bold"),
                (clipboard_status, "dim"),
            ),
            title="[bold]Relic[/bold]",
            border_style="green",
        )
    )
